### PR TITLE
Remove webcomponentsjs dependency

### PR DESCRIPTION
**Pull request by limonte**
It's already included in Polymer:

- https://github.com/Polymer/polymer/blob/1.x/bower.json#L28
- https://github.com/Polymer/polymer/blob/master/bower.json#L25

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout/57)

### CODE REVIEW

**Comment by platosha** [comment]
Looks bad to me.

It is not that the dependency is removed, the demos and the tests still depend on it. Not a good idea to undeclare still existing dependencies IMO.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/57#-:-KfkywDDrZAVwfSQxJp_:b-hqcwtr)*

**Comment by limonte** [comment]
> It is not that the dependency is removed

The dependency is not removed. We are including polymer and we are 100% sure that polymer includes webcomponentsjs. So why duplicate including and create the potential dependencies conflict situation? 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/57#-:-Kfl13PRtqQ-qeGO-PhX:b-aml94x)*

**Comment by limonte** [comment]
Besides, there's a golden rule: less code = less bugs. No need to maintain another one dependency, polymer team is doing that for us.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/57#-:-Kfl1Xxg5nw_DSXZAVoS:b-ez5xve)*

**Comment by platosha** [comment]
> we are 100% sure that polymer includes webcomponentsjs

this could change anytime. Bower.json contents are not a part of Polymer’s API.

Also, it is pretty surprising to see indirect dependencies in use anywhere. There’s a golden rule: explicit is better then implicit.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/57#-:-Kfl1rJ_JmQREEXLoRKC:bdv7cs8)*

**Comment by tomivirkki** [comment]
It's a common practice not to rely on transitive dependencies if you explicitly import something. Polymer elements follow the same practice https://github.com/PolymerElements/paper-input/blob/master/bower.json#L49

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/57#-:-Kfl1vNjNds00gsNqH9T:b-rpqda6)*

**Pull request closed without merging**
