### PR TITLE
Add visual tests for Polymer 2

### PR DESCRIPTION
**Pull request by limonte**
Connected to https://github.com/vaadin/vaadin-split-layout/issues/63

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout/68)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/visual/test.js, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/68#-KkPFwmXgleAfQJROJRW:-KkPFwmXgleAfQJROJRX:b41p2ua) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/2ba4f5ea3f846024b82af2794f0feaea0288fce4/test/visual/test.js#L15)):*
> ```JavaScript
>   rootSuite
>     .before(wait)
>     .after(goToAboutBlank);
> ```

Good idea to use the `after` `before` here.
Nit: If we are using these two functions just once, I think it would be simpler to inline them into the  `after` `before` blocks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/68)*

**Comment by manolo** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/68)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/visual/test.js, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/68#-KkPFwmXgleAfQJROJRW:-KkPdSaM_jY8lH5ES4uO:b-ygkne4) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/2ba4f5ea3f846024b82af2794f0feaea0288fce4/test/visual/test.js#L15)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Good idea to use the `after` `before` here.
Nit: If we are using these two functions just once, I think it would be simpler to inline them into the  `after` `before` blocks
</blockquote></details>

I'd rather leave it this way to keep the gemini configuration same and universal for all our components, e.g. [button](https://github.com/vaadin/vaadin-button/blob/master/test/visual/test.js) and [text-field](https://github.com/vaadin/vaadin-text-field/blob/master/test/visual/test.js) have the same configuration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/68)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/68#-:-KkRKT7cqqrDFZgsG3cN:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/68#-:-KkUWM6zewoqM68iMI19:bnfp4nl)*

**Comment by platosha** [comment]
Maybe rebase?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/68#-:-KkUWW-ksihezFzx77rc:b-87pabm)*

**Pull request merged**
