### PR TITLE
Switch from JSHint + JSCS to ESLint

### PR DESCRIPTION
**Pull request by limonte**
Reason: ESLint checks your code for bugs and other problems besides coding style, read more: https://www.sitepoint.com/comparison-javascript-linting-tools/

ESLint catches errors which JSHint + JSCS can't handle:

Based on:  https://github.com/Polymer/polymer/blob/master/.eslintrc.json

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout/31)

### CODE REVIEW

**Comment by samiheikki** [comment]
Does any of the Polymer Elements use ESLint?  I was looking at https://github.com/PolymerElements/paper-input and https://github.com/PolymerElements/iron-list.

**Comment by limonte** [comment]
It doesn't seem that Polymer Elements are using any JS linter at all.

**Comment by manolo** [comment]
Whatever linter we use, should be common in all our components, and we should do at once. 

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/31#-:-KXjTI422IBXomyF77M9:b-26amwu)*

**Comment by limonte** [comment]
Sure, but I can't create 1 PR to several repos :) If this PR will be approved I'll copy the same config to all our components.

**Comment by manolo** [comment]
Exactly. So once this is approved, I think this should be held and merge with all the others

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/31#-:-KXjsDbvvOcvXgML9JEU:baw3955)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/31#-:-KXk-no2T1SPZ8XuMFDs:bnfp4nl)*

**Pull request merged**
