### PR TITLE
make lint happy

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout/28)

### CODE REVIEW

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-split-layout.html, line 163 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/28#-KXeSIRX5gpaALKOhuH4:-KXeSIRX5gpaALKOhuH5:bbo81yh) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/4437a67e440e66a37fec9d76f8229406102de27f/vaadin-split-layout.html#L163)):*
> ```HTML
>             this._primaryChild = child;
>             Polymer.dom(child).setAttribute('vaadin-split-layout', 'primary');
>           } else if (i == 1) {
> ```

the same should be for this line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/28)*

**Comment by tomivirkki** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/28#-:-KXeVLse30oEkOgmQRRc:bnfp4nl)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-split-layout.html, line 163 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/28#-KXeSIRX5gpaALKOhuH4:-KXeVc-5O7AH15cA3rxB:brcxdcx) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/4437a67e440e66a37fec9d76f8229406102de27f/vaadin-split-layout.html#L163)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

the same should be for this line
</blockquote></details>

Why? if `i` is always a number because of the foreach spec we don't need make js runtime check for types here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/28)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/28)*

**Comment by limonte** [comment]
http://www.2ality.com/2011/12/strict-equality-exemptions.html

**Pull request merged**
