### PR TITLE
Visual testing fix: replace gemini-express by gemini-polyserve

### PR DESCRIPTION
**Pull request by limonte**
Related to https://github.com/vaadin/vaadin-element-skeleton/pull/24

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout/51)

### CODE REVIEW

**Comment by manolo** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[.travis.yml, line 24 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/51#-KdBGY3xys6cZjDhxsc0:-KdBGY3xys6cZjDhxsc1:bpw3day) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/95241f9b9314419fb975ef7ed5e6fcb4ba4a366d/.travis.yml#L24)):*
> ```YAML
> 
> script:
>   - polyserve &
> ```

How do you know that polyserve is installed in the system?
Shouldn't you add this dependency to the package.json file and run it from `node_modules/.bin/polyserve` so as you don't trust in the system installed version ?

Another question is if you are sure that all background processes are cleaned up when travis process exits  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/51)*

**Comment by limonte** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 24 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/51#-KdBGY3xys6cZjDhxsc0:-KdBN5ZMZffhFZVami0u:bq7hua1) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/95241f9b9314419fb975ef7ed5e6fcb4ba4a366d/.travis.yml#L24)):*
> How do you know that polyserve is installed in the system?
Shouldn't you add this dependency to the package.json

Done.

> run it from node_modules/.bin/polyserve so as you don't trust in the system installed version ?

I don't believe in the possibility of another polyserve installed in the system and I disagree with complicating of travis config. 

> Another question is if you are sure that all background processes are cleaned up when travis process exits

I don't need to care about this and I'm against disagree with unnecessary complicating the config. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/51)*

**Comment by manolo** [comment]
Same comments than in the skeleton. Don't run polyserve from command line, but make the tests run it so as we don't break gulp and wct scripts. :-1:

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/51#-:-KdLJ6bFcW9pS_80GtMd:b-2kt0q7)*

**Comment by limonte** [comment]
Done in the same ways as the skeleton: by splitting `index.html` to `default.html` and `customized.html`

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/51#-:-Kde42GeBgj3-QrkOGRO:baxpbhl)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/visual/test.js, line 7 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/51#-Kde9AfWN-9xmuV4mxj4:-Kde9AfWN-9xmuV4mxj5:bnoxoyw) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/0e59009903db70d8259e43c29964b589f4c99f35/test/visual/test.js#L7)):*
> ```JavaScript
>       .setUrl('/default.html')
>       .setCaptureElements('#default')
>       .capture('default', {}, function(actions, find) {
> ```

Nit: mind to extract this to a wait method? in input already it is in this way. Not a blocker though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/51#-:-Kde9O1JqlWHCLyv1PtW:bnfp4nl)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[test/visual/test.js, line 7 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/51#-Kde9AfWN-9xmuV4mxj4:-Kde9Z880l_dsLJWY_Le:b-wt9su8) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/0e59009903db70d8259e43c29964b589f4c99f35/test/visual/test.js#L7)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Nit: mind to extract this to a wait method? in input already it is in this way. Not a blocker though
</blockquote></details>

Yup, I have that on my mind. Will do later, not in scope of this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/51)*

**Pull request merged**
