### PR TITLE
Adding demo for hidden splitter.

### LINKED ISSUE #62: `splitterHidden` property
### Use Case

There is a layout, where one of two content elements is optionally hidden.

When one of the content elements is hidden, resizing the split is not applicable anymore, the splitter and the split layout functions become unnecessary. In this case, it is expected that the splitter is hidden.

### Suggested Solution

Add `splitterHidden: Boolean` property, false by default. When true, the splitter is hidden.

### Usage Example

Users can hide one of the content elements and the splitter at the same time by using bindings in a parent scope:

```html
<vaadin-split-layout splitter-hidden="[[_descriptionHidden]]">
  <div id="main"></div>
  <div id="description" hidden="[[_descriptionHidden]]">
</vaadin-split-layout>
```

### PR DESCRIPTION
**Pull request by manolo**
Fixes #62

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout/76)

### CODE REVIEW

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/theming.html, line 60 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/76#-Kq1s0dwKjCmMwymRo0L:-Kq1s0dwKjCmMwymRo0M:b52vp0t) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/f063a5779da7afbcbb221000eb30cdf5d82497a8/demo/theming.html#L60)):*
> ```HTML
>         <dom-bind>
>           <template is="dom-bind">
>             <label><input aria-label="Select Row" type="checkbox" checked="{{_hideLeft::change}}">Hide Left Section</label>
> ```

`vaadin-checkbox` will look nicer here:

```html
<vaadin-checkbox checked="{{_hideLeft::change}}" aria-label="Select Row">
  Hide Left Section
</vaadin-checkbox>
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/76)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[demo/theming.html, line 60 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/76#-Kq1s0dwKjCmMwymRo0L:-Kq21MI4kNz33b5KqnF2:b-vjk6nc) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/f063a5779da7afbcbb221000eb30cdf5d82497a8/demo/theming.html#L60)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

`vaadin-checkbox` will look nicer here:

```html
<vaadin-checkbox checked="{{_hideLeft::change}}" aria-label="Select Row">
  Hide Left Section
</vaadin-checkbox>
```
</blockquote></details>

I’m not sure about adding the vaadin-checkbox dev-dependency in the split-layout just for a demo. Also depending on an unfinished component sounds not ok. I agree that the demo could be nicer though.
Also the default theme for vaadin-checkbox is a native look, we would need to depend on themes, but we tried to avoid that loop dependency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/76)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/76#-:-Kq21ZG8d0qOtvgyTD-z:bnfp4nl)*

**Comment by limonte** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/76)*

**Comment by Toshegg** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/76#-:-Kq2CVVJMNSqFJemblmX:bnfp4nl)*

**Pull request merged**
