### PR TITLE
CI tests: Enable IE11, bump iOS version

### LINKED ISSUE #70: Add IE11 to test platforms

### PR DESCRIPTION
**Pull request by platosha**
Fixes #70

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout/71)

### CODE REVIEW

**Comment by samiheikki** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[wct.conf.js, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/71#-KlMl-41Qw8fei7QJMwz:-KlMl-41Qw8fei7QJMx-:b-d3z6tm) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6d60c02752c6fbcd9e74371f831d16f0463106f7/wct.conf.js#L12)):*
> ```JavaScript
>       // iPad simulator does not start on Saucelabs for some reason
>       // TODO: enable back
>       // 'macOS 10.12/ipad@10.3',
> ```

Any reason why the ipad simulator not starting? Was with working with the 9.3 version?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/71)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[wct.conf.js, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/71#-KlMl-41Qw8fei7QJMwz:-KlNB24rJPNXbYRunZoO:b87pj3l) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6d60c02752c6fbcd9e74371f831d16f0463106f7/wct.conf.js#L12)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Any reason why the ipad simulator not starting? Was with working with the 9.3 version?
</blockquote></details>

Was working, does not work anymore after the order of scripts changed in `test/index.html`.

iPhone 10.3 works fine, iPad 10.3 does not start at all. I guess, the iPad Simulator of this newest version is just not ready in SauceLabs VMs yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/71)*

**Comment by platosha** [comment]
@limonte true that, but the simulator startup on SauceLabs is not in under our control. The total build time here is still okay though.

We should migrate to newer iOS on CI at some point anyway. Having IE11 and modern iOS tests enabled is more relevant than iOS 9.

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[wct.conf.js, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/71#-KlMl-41Qw8fei7QJMwz:-KlPPU59cbNcqJkLPa3h:byxepnv) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6d60c02752c6fbcd9e74371f831d16f0463106f7/wct.conf.js#L12)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Was working, does not work anymore after the order of scripts changed in `test/index.html`.

iPhone 10.3 works fine, iPad 10.3 does not start at all. I guess, the iPad Simulator of this newest version is just not ready in SauceLabs VMs yet.
</blockquote></details>

Can you try 'OS X 10.11/ipad@10.2' instead, it works in other elements

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/71)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[wct.conf.js, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/71#-KlMl-41Qw8fei7QJMwz:-KlSYe6K9_4xhx1nqAs_:b-w2h1wm) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6d60c02752c6fbcd9e74371f831d16f0463106f7/wct.conf.js#L12)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Can you try 'OS X 10.11/ipad@10.2' instead, it works in other elements
</blockquote></details>

It does not work here, mock-interactions.js touch events + the polyfill do not work nicely in iOS 10.2.

I mean, the element itself works fine, but the dynamic tests for dragging the splitter will get errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/71)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/71#-:-KlX7zzWlzSOF6i60y6C:bnfp4nl)*

**Comment by samiheikki** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/71#-:-KlXB_IW_55VwjttHosm:bnfp4nl)*

**Pull request merged**
