### PR TITLE
Add Google Maps example

### LINKED ISSUE #50: Resizing isn't working with complex content
If panels contain complex content (e.g. Google Maps iframes), then resizing isn't working properly. 

In case of complex content, it takes more time to rerender panels and if mouse moves faster than rerendering process than resizing stops working.

Live example: https://github.com/vaadin/vaadin-split-layout/pull/49

### PR DESCRIPTION
**Pull request by limonte**
Fixes #50 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout/49)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/integration.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49#-KcI_C-svMmj8_36-EI1:-KcI_C-svMmj8_36-EI2:be8yvy5) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6440f7a19c5b54948163d34f205e9857c502bf7e/demo/integration.html#L31)):*
> ```HTML
>         <vaadin-split-layout style="height: 300px">
>           <div>
>             <iframe src="//maps.google.com/maps?q=Turku&output=embed"></iframe>
> ```

why not use `<google-map>` web component instead. We might need an api key, but I think should be more interesting for the demo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/integration.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49#-KcI_C-svMmj8_36-EI1:-KcI_q_T_PEJy-tdZ-eW:bym1vea) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6440f7a19c5b54948163d34f205e9857c502bf7e/demo/integration.html#L31)):*
> why not use <google-map> web component instead. 

Why should I use it? `<iframe>` is the dead-simple bullet-proof solution. I don't want to rely on one more component for such a simple task. Also, as you mentioned I need to make a Google project to get the API key which makes this example even more harder to maintain.

We're fighting for simplicity as far as I remember :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/integration.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49#-KcI_C-svMmj8_36-EI1:-KcIcn16gO6GL_wXNTnX:bqg9t0e) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6440f7a19c5b54948163d34f205e9857c502bf7e/demo/integration.html#L31)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

> why not use <google-map> web component instead. 

Why should I use it? `<iframe>` is the dead-simple bullet-proof solution. I don't want to rely on one more component for such a simple task. Also, as you mentioned I need to make a Google project to get the API key which makes this example even more harder to maintain.

We're fighting for simplicity as far as I remember :)
</blockquote></details>

Ok then. 
But in this example the component does not behave agile and it seems difficult to move the icon.
Seems like when moving the handle over the map it eats the drag events.
Have you experienced the same problem?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/integration.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49#-KcI_C-svMmj8_36-EI1:-KcIduFb6birI3t7RtmP:b-6v3iuy) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6440f7a19c5b54948163d34f205e9857c502bf7e/demo/integration.html#L31)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Ok then. 
But in this example the component does not behave agile and it seems difficult to move the icon.
Seems like when moving the handle over the map it eats the drag events.
Have you experienced the same problem?
</blockquote></details>

Exactly! I reported it couple of minutes ago: https://github.com/vaadin/vaadin-split-layout/issues/50

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/integration.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49#-KcI_C-svMmj8_36-EI1:-KcNXC-6-Mo5AvjtnU5Z:bichpvx) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6440f7a19c5b54948163d34f205e9857c502bf7e/demo/integration.html#L31)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Exactly! I reported it couple of minutes ago: https://github.com/vaadin/vaadin-split-layout/issues/50
</blockquote></details>

So, IMO we shouldn't merge this PR until that is fixed.
I don't think this demo would be a good cover letter for our component until it behaves agile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49)*

**Comment by limonte** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/integration.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49#-KcI_C-svMmj8_36-EI1:-KcNfA8sNyaLLcLNIMOd:b-g19d4h) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6440f7a19c5b54948163d34f205e9857c502bf7e/demo/integration.html#L31)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

So, IMO we shouldn't merge this PR until that is fixed.
I don't think this demo would be a good cover letter for our component until it behaves agile.
</blockquote></details>

I added fix, but unfortunately I have no idea how to test that change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49)*

**Comment by platosha** [comment]
Nice touch! :thumbsup:

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[vaadin-split-layout.html, line 309 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49#-KcNi10C7fvWd8ggWeaK:-KcNi10C7fvWd8ggWeaL:be1hzjd) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/12a8b87ca55d84146cf0c6a5eedb86abd1781876/vaadin-split-layout.html#L309)):*
> ```HTML
>         }
> ```

Unnecessary empty line?

---

*[demo/integration.html, line 31 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49#-KcNiLHuXH-711gEo9Vh:-KcNiLHvSXg6yRvzv089:blcosv4) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/12a8b87ca55d84146cf0c6a5eedb86abd1781876/demo/integration.html#L31)):*
> ```HTML
>         <vaadin-split-layout style="height: 300px">
>           <div>
>             <iframe src="//maps.google.com/maps?q=Turku&output=embed"></iframe>
> ```

Could iframes be used as children directly, without wrapper divs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49#-:-KcNilMldjo7u94g0c2M:b-81n5ko)*

**Comment by limonte** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-split-layout.html, line 309 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49#-KcNi10C7fvWd8ggWeaK:-KcNjlYbxdCjxwsMu9Jd:b-hfpv0l) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/12a8b87ca55d84146cf0c6a5eedb86abd1781876/vaadin-split-layout.html#L309)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Unnecessary empty line?
</blockquote></details>

removed

---

*[demo/integration.html, line 31 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49#-KcNiLHuXH-711gEo9Vh:-KcNjndmV5VaHES24nc6:bc0ehhh) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/12a8b87ca55d84146cf0c6a5eedb86abd1781876/demo/integration.html#L31)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Could iframes be used as children directly, without wrapper divs?
</blockquote></details>

nope, but that's fine by me as it always better to wrap an iframe in a container and set iframe's width/height to 100% to fill a container.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49)*

**Comment by limonte** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/integration.html, line 31 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49#-KcNiLHuXH-711gEo9Vh:-KcNmlYjhzXTxlq_cHRh:bfvrybh) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/12a8b87ca55d84146cf0c6a5eedb86abd1781876/demo/integration.html#L31)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

nope, but that's fine by me as it always better to wrap an iframe in a container and set iframe's width/height to 100% to fill a container.
</blockquote></details>

Actually it is possible :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/integration.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49#-KcI_C-svMmj8_36-EI1:-KcNnaZAsbJVSrQXg2ZG:b-wepkdx) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6440f7a19c5b54948163d34f205e9857c502bf7e/demo/integration.html#L31)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I added fix, but unfortunately I have no idea how to test that change
</blockquote></details>

Testing should be pretty straitforward:

1. dispatch dragstart
2. expect pointerEvents style on the child panes to equal none

and the second test to ensure the value returns back to initial:

1. set pointerEvents to auto explicitly
2. dispatch dragstart and dragend
3. expect pointerEvents style on the child panes to be back to `'auto'`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49)*

**Comment by limonte** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/integration.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49#-KcI_C-svMmj8_36-EI1:-KcSVmouQvYqQCPZJvJK:byeed48) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6440f7a19c5b54948163d34f205e9857c502bf7e/demo/integration.html#L31)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Testing should be pretty straitforward:

1. dispatch dragstart
2. expect pointerEvents style on the child panes to equal none

and the second test to ensure the value returns back to initial:

1. set pointerEvents to auto explicitly
2. dispatch dragstart and dragend
3. expect pointerEvents style on the child panes to be back to `'auto'`
</blockquote></details>

Appreciate your help here! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/49#-:-KcSe7KOEzDlX2HM4GA9:bnfp4nl)*

**Pull request merged**
