### PR TITLE
Add variants dependencies to bower.json

### LINKED ISSUE #52: Add variants dependencies to main bower.json
- Default to Polymer v1, have "variants" for "2.x"
- Use `polymer install --variants` in testing

### PR DESCRIPTION
**Pull request by limonte**
Fixes #52

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout/53)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KemxD0x6NxPK06DhK5J:-KemxD0x6NxPK06DhK5K:bf7qb75) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/a5737d2a0b21cb400e3ef9a3065a01fb36afcfd4/.travis.yml#L16)):*
> ```YAML
> install:
>   - npm install
>   - npm install -g polymer-cli@0.18.0-pre.13
> ```

I'm not positive about installing npm dependencies globally. 
It implies that they are installed in the global node_modules folder of the user, instead of in the node_modules folder of this 
Hence it has two problems:
1.- we are polluting global folder with our version, and might prejudice other users' builds if they don't care on installing these dependencies and trust on the system. I'm not assuming that perhaps travis could take care of removing that stuff.
2.- we don't take advantage of the configured cache for this project, we cache node_modules in this folder, not in the global one.

So in my opinion, we should remove the `-g` flag, and force always to use `node_modules/.bin/polymer` command, although I know that travis adds that folder to the users PATH, but probably not in the first position.
 

---

*[.travis.yml, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KemzAZ_-c5xbOphFMvv:-KemzAZagcDM1SF00xn_:bdwtd6s) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/a5737d2a0b21cb400e3ef9a3065a01fb36afcfd4/.travis.yml#L25)):*
> ```YAML
> script:
>   - ([ "$TRAVIS_EVENT_TYPE" = "pull_request" ] || gemini test test/visual)
>   - xvfb-run -s '-screen 0 1024x768x24' wct
> ```

shouldn't we run tests against both variants ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53)*

**Comment by limonte** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KemxD0x6NxPK06DhK5J:-Ken3gwR8Z_ZHTtfTK3O:b-go9y6h) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/a5737d2a0b21cb400e3ef9a3065a01fb36afcfd4/.travis.yml#L16)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I'm not positive about installing npm dependencies globally. 
It implies that they are installed in the global node_modules folder of the user, instead of in the node_modules folder of this 
Hence it has two problems:
1.- we are polluting global folder with our version, and might prejudice other users' builds if they don't care on installing these dependencies and trust on the system. I'm not assuming that perhaps travis could take care of removing that stuff.
2.- we don't take advantage of the configured cache for this project, we cache node_modules in this folder, not in the global one.

So in my opinion, we should remove the `-g` flag, and force always to use `node_modules/.bin/polymer` command, although I know that travis adds that folder to the users PATH, but probably not in the first position.
 
</blockquote></details>

`-g` removed, still no need to specify  `node_modules/.bin/` for `polymer`, Travis is smart enough to find it.

---

*[.travis.yml, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KemzAZ_-c5xbOphFMvv:-Ken3vEY0zh72-ecGNKG:bbw5lox) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/a5737d2a0b21cb400e3ef9a3065a01fb36afcfd4/.travis.yml#L25)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

shouldn't we run tests against both variants ?
</blockquote></details>

Oops, I forgot to revert this. Done, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KemxD0x6NxPK06DhK5J:-KenLGVUAD2o-vjKSjAW:bcneeju) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/a5737d2a0b21cb400e3ef9a3065a01fb36afcfd4/.travis.yml#L16)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

`-g` removed, still no need to specify  `node_modules/.bin/` for `polymer`, Travis is smart enough to find it.
</blockquote></details>

travis is not smart, just the PATH variable. Are you sure node_modules/.bin is before than   the folder wherever npm leaves files when installed as global

---

*[.travis.yml, line 27 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KenL6eO8ZTAu1PyOHYo:-KenL6eP0IXxeW9_OFrb:b-bb1bt6) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/2a277493a6b36e9f1c0d06014b60b907092791c0/.travis.yml#L27)):*
> ```YAML
>   - xvfb-run -s '-screen 0 1024x768x24' wct
>   - rm -rf bower_components
>   - cp bower-polymer2.json bower.json
> ```

you removed bower-2.0, where is bower-polymer2 ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53)*

**Comment by limonte** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KemxD0x6NxPK06DhK5J:-KenPVV7ZrtIV5LU_mw-:b-rfuaoi) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/a5737d2a0b21cb400e3ef9a3065a01fb36afcfd4/.travis.yml#L16)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

travis is not smart, just the PATH variable. Are you sure node_modules/.bin is before than   the folder wherever npm leaves files when installed as global
</blockquote></details>

I'm not quite sure I understand your question, but I made a test branch with `echo $PATH`: https://travis-ci.org/vaadin/vaadin-split-layout/builds/209363454

---

*[.travis.yml, line 27 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KenL6eO8ZTAu1PyOHYo:-KenPYmBGZu4jbQmJriB:b-kwuvpc) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/2a277493a6b36e9f1c0d06014b60b907092791c0/.travis.yml#L27)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

you removed bower-2.0, where is bower-polymer2 ? 
</blockquote></details>

`bower-polymer2.json` is generated automatically by `polymer install --variants`, no need to keep it in repo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KemxD0x6NxPK06DhK5J:-KeoDxz07F7J7hHBcqWp:bj69lm) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/a5737d2a0b21cb400e3ef9a3065a01fb36afcfd4/.travis.yml#L16)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I'm not quite sure I understand your question, but I made a test branch with `echo $PATH`: https://travis-ci.org/vaadin/vaadin-split-layout/builds/209363454
</blockquote></details>

I added a couple of commands to your branch:

```
 install:
   - npm install
   - npm install -g bower
+  - npm install -g polymer
   - bower install

 script:
   - echo $PATH
+  - which polymer
+  - which bower
```

And the result is that travis cannot find the polymer command https://travis-ci.org/vaadin/vaadin-split-layout/builds/209446565

```
$ echo $PATH
/home/travis/.rvm/gems/ruby-2.3.1/bin:/home/travis/.rvm/gems/ruby-2.3.1@global/bin:/home/travis/.rvm/rubies/ruby-2.3.1/bin:/home/travis/.rvm/bin:/home/travis/.nvm/versions/node/v7.7.2/bin:/home/travis/firefox-latest/firefox:/home/travis/bin:/home/travis/.local/bin:/home/travis/.pyenv/shims:/home/travis/.phpenv/shims:/home/travis/gopath/bin:/home/travis/.local/bin:/opt/pyenv/bin:/opt/python/2.7.12/bin:/opt/python/3.5.2/bin:/usr/local/phantomjs/bin:/usr/local/phantomjs:/home/travis/perl5/perlbrew/bin:./node_modules/.bin:/usr/local/maven-3.1.1/bin:/home/travis/.kiex/elixirs/elixir-1.0.4/bin:/home/travis/.kiex/bin:/usr/local/gradle/bin:/usr/local/clang-3.5.0/bin:/home/travis/.gimme/versions/go1.6.3.linux.amd64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.phpenv/bin
The command "echo $PATH" exited with 0.0.02s

$ which polymer
The command "which polymer" exited with 1.0.05s

$ which bower
/home/travis/.nvm/versions/node/v7.7.2/bin/bower
The command "which bower" exited with 0.0.03s

$ polymer --version
/home/travis/build.sh: line 62: polymer: command not found
The command "polymer --version" exited with 127.

```

So when installing as global and not locally command could be not found, and would take anything it finds in the path if there is.

Analysing the path it seems that `./node_modules/.bin` has more preference than `/usr/local/bin` which probably would be the global folder for npm binaries if the user has enough permissions.

In my opinion, trusting in travis order is not a good strategy, because we depend on they not changing their scripts. Otherwise installing in local, and prepending the path of the command we want to run is safer.  Your argument is that you want to have less stuff in the `.travis.yml` file.  But I'd rather to know exactly what is being executed in the script.

So, I would 
 1- add polymer dependency in package.json so as `npm i` install it, instead of running twice npm which slow down the installation.
 2- prepend the path of the command to execute, so as any reader knows exactly what is being executed without having to figure out any magic of the CI server. Also he can copy and paste to run manually anything locally.

---

*[.travis.yml, line 27 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KenL6eO8ZTAu1PyOHYo:-KeoGmlhvzq2Zxe3WCgE:b-z3n3z) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/2a277493a6b36e9f1c0d06014b60b907092791c0/.travis.yml#L27)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

`bower-polymer2.json` is generated automatically by `polymer install --variants`, no need to keep it in repo.
</blockquote></details>

Nice feature, it saves that we have to maintain it. thanks for clarification. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53)*

**Comment by limonte** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KemxD0x6NxPK06DhK5J:-Keqztu-jK61Z40cv4KJ:b51nrhu) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/a5737d2a0b21cb400e3ef9a3065a01fb36afcfd4/.travis.yml#L16)):*
> npm install -g polymer

> And the result is that travis cannot find the polymer command

Travis cannot find the polymer command because it wasn't installed. You need to install `polymer*-cli*`. Bad naming :/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KemxD0x6NxPK06DhK5J:-Ker67f5hA_CjHVNJRVs:b-r7ejbs) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/a5737d2a0b21cb400e3ef9a3065a01fb36afcfd4/.travis.yml#L16)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

> npm install -g polymer

> And the result is that travis cannot find the polymer command

Travis cannot find the polymer command because it wasn't installed. You need to install `polymer*-cli*`. Bad naming :/
</blockquote></details>

Can you rerun again corrected. If it,s in usr/local/bin it's OK not adding the prefix since it,s after in the path variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53)*

**Comment by limonte** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KemxD0x6NxPK06DhK5J:-Ker6uFHMfTd03n8vHvG:b4u26ds) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/a5737d2a0b21cb400e3ef9a3065a01fb36afcfd4/.travis.yml#L16)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Can you rerun again corrected. If it,s in usr/local/bin it's OK not adding the prefix since it,s after in the path variable.
</blockquote></details>

Sure, here's the output: https://travis-ci.org/vaadin/vaadin-split-layout/builds/209650945

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KemxD0x6NxPK06DhK5J:-KerVivwSDkO-twQNDUR:bp2fiff) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/a5737d2a0b21cb400e3ef9a3065a01fb36afcfd4/.travis.yml#L16)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Sure, here's the output: https://travis-ci.org/vaadin/vaadin-split-layout/builds/209650945
</blockquote></details>

So anything installed globally has preference over installed locally, so I would modify the path by setting PATH=./node_modules/.bin:$PATH or adding the prefix. Apparently Travis cleans the global  folder, but  I  don't  thing it,s guaranteed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53)*

**Comment by limonte** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KemxD0x6NxPK06DhK5J:-KermO_-5tqb6ue5eHYr:b-m038ce) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/a5737d2a0b21cb400e3ef9a3065a01fb36afcfd4/.travis.yml#L16)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

So anything installed globally has preference over installed locally, so I would modify the path by setting PATH=./node_modules/.bin:$PATH or adding the prefix. Apparently Travis cleans the global  folder, but  I  don't  thing it,s guaranteed
</blockquote></details>

I don't really understand your worries about paths. Each testing environment is isolated and there can't be installed anything except what you have in `.travis.yml`. If at some point in future I will need to install polymer both globally and locally (possibility of that is very low) then I will use the prefix. For now, with addition the prefix we're just making the config line longer and less readable without any strong reasons for that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KemxD0x6NxPK06DhK5J:-Kerpne_hNJORs-CsY01:bb2isk2) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/a5737d2a0b21cb400e3ef9a3065a01fb36afcfd4/.travis.yml#L16)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I don't really understand your worries about paths. Each testing environment is isolated and there can't be installed anything except what you have in `.travis.yml`. If at some point in future I will need to install polymer both globally and locally (possibility of that is very low) then I will use the prefix. For now, with addition the prefix we're just making the config line longer and less readable without any strong reasons for that.
</blockquote></details>

OK, not a blocker let's discuss face to face on monday, move polymer-cli to package. json so as we don't run npm twice,  and go ahead with the merge

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53)*

**Comment by limonte** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53#-KemxD0x6NxPK06DhK5J:-Kes0bqnmAkpNxMDyc3_:b-qfw9x0) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/a5737d2a0b21cb400e3ef9a3065a01fb36afcfd4/.travis.yml#L16)):*
> move polymer-cli to package. json so as we don't run npm twice, and go ahead with the merge

Done.

> let's discuss face to face on monday

:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/53)*

**Pull request merged**
