### PR TITLE
Polymer Hybrid Element Compliant.

### LINKED ISSUE #40: Support Polymer 2.0
Use Hybrid mode to continue supporting Polymer 1.x

### PR DESCRIPTION
**Pull request by manolo**
Fixes #40

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout/47)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[.travis.yml, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCAYekrupcFFqK27xM:-KaCAYekrupcFFqK27xN:b-hqdplq) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/edb218d6e257abca66b0aae89a11e1b96f75446f/.travis.yml#L9)):*
> ```YAML
>   directories:
>     - bower_components
>     - node_modules
> ```

We still want to cache node_modules

---

*[package.json, line 3 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCAj02jMCTOXpF3GQt:-KaCAj03tBl4N2lQBhKc:b-p4ljq3) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/887d0ff520afce807b712d79edf0df508ded1a8d/package.json#L3)):*
> ```JSON
> {
>   "name": "vaadin-split-layout",
>   "version": "2.0.0-preview",
> ```

This should probably be 1.0.0

---

*[vaadin-split-layout.html, line 153 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCBJVHtEEt5ijUfgcD:-KaCBJVHtEEt5ijUfgcE:bdk3mwg) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/887d0ff520afce807b712d79edf0df508ded1a8d/vaadin-split-layout.html#L153)):*
> ```HTML
> ```html
> <custom-style>
>   <style is="custom-style">
> ```

If P1.7 supports `<custom-style>`, `is=custom-style` is no longer needed

---

*[vaadin-split-layout.html, line 275 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCBc44aD5SsaD-0HtP:-KaCBc44aD5SsaD-0HtQ:btnhvpd) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/887d0ff520afce807b712d79edf0df508ded1a8d/vaadin-split-layout.html#L275)):*
> ```HTML
>         children.filter(function(child) {
>           if (child.classList.contains('splitter-handle')) {
>             Polymer.dom(child).setAttribute('slot', 'handle');
> ```

Side effects in filter function feels wrong

---

*[wct.conf.js, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCBj_fjHq8UrKpmK7H:-KaCBj_fjHq8UrKpmK7I:b-op8lcm) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/887d0ff520afce807b712d79edf0df508ded1a8d/wct.conf.js#L16)):*
> ```JavaScript
>         'Windows 10/firefox@50',
>         'Windows 10/microsoftedge@14',
>         // 'Windows 10/internet explorer@11',
> ```

We can't disable testing these browsers with P1. Maybe we also need wct.conf-2.0.js or something?

---

*[demo/custom.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCC6nIIGdUAqJnf9ef:-KaCC6nIIGdUAqJnf9eg:b8ds14g) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/edb218d6e257abca66b0aae89a11e1b96f75446f/demo/custom.html#L29)):*
> ```HTML
>     <demo-snippet>
>       <template>
>         <style is="custom-style">
> ```

<custom-style> wrapper needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47)*

**Comment by limonte** [comment]
Review status: 0 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[.travis.yml, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCAYekrupcFFqK27xM:-KaCCozmlip8eESmeV4x:b25on1u) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/edb218d6e257abca66b0aae89a11e1b96f75446f/.travis.yml#L9)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

We still want to cache node_modules
</blockquote></details>

Removing just Bower cache will solve your issue with Travis caching https://github.com/vaadin/vaadin-element-skeleton/pull/10

Please revert npm cache, it has some heavy deps and cachimg them will speed up build.

---

*[gulpfile.js, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaBRrAfhxQ9OAXZdG6h:-KaBRrAgTbHi1pIy6xCv:bskxxrw) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/887d0ff520afce807b712d79edf0df508ded1a8d/gulpfile.js#L35)):*
> ```JavaScript
> });
> 
> gulp.task('test', ['lint'], function(done) {
> ```

You're now using this task in Travis, I'm wondering why it was added?

---

*[wct.conf.js, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaBSW5FUWLSHBvDvNZr:-KaBSW5FUWLSHBvDvNZs:bh1xqic) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/edb218d6e257abca66b0aae89a11e1b96f75446f/wct.conf.js#L1)):*
> ```JavaScript
> var args = require('yargs').argv;
> ```

`yargs` dependency should be  also removed from `package.json` as we're not using it anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47)*

**Comment by manolo** [comment]
Review status: 0 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[.travis.yml, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCAYekrupcFFqK27xM:-KaDb1ABUy44u34Qg7fk:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/edb218d6e257abca66b0aae89a11e1b96f75446f/.travis.yml#L9)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Removing just Bower cache will solve your issue with Travis caching https://github.com/vaadin/vaadin-element-skeleton/pull/10

Please revert npm cache, it has some heavy deps and cachimg them will speed up build.
</blockquote></details>

Done.

---

*[gulpfile.js, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaBRrAfhxQ9OAXZdG6h:-KaDbBYsbXUgjeWU7gse:b-f7g3af) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/887d0ff520afce807b712d79edf0df508ded1a8d/gulpfile.js#L35)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

You're now using this task in Travis, I'm wondering why it was added?
</blockquote></details>

It's a convenience method for local testing.
I run this frequently, and it is already in other components. Is it there any impact to leave this here?

---

*[package.json, line 3 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCAj02jMCTOXpF3GQt:-KaDbsfU2SygKZg9Gesg:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/887d0ff520afce807b712d79edf0df508ded1a8d/package.json#L3)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This should probably be 1.0.0
</blockquote></details>

Done.

---

*[vaadin-split-layout.html, line 153 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCBJVHtEEt5ijUfgcD:-KaDcaPYQJskxsSPcI19:b-xk2wf1) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/887d0ff520afce807b712d79edf0df508ded1a8d/vaadin-split-layout.html#L153)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

If P1.7 supports `<custom-style>`, `is=custom-style` is no longer needed
</blockquote></details>

It's still needed, try to remove the `is` attribute in `custom.html` line 165, and you can see that `fill` colours do not change.

---

*[vaadin-split-layout.html, line 275 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCBc44aD5SsaD-0HtP:-KaDd6pedNfN6Z6va-V6:b-qw53fk) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/887d0ff520afce807b712d79edf0df508ded1a8d/vaadin-split-layout.html#L275)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Side effects in filter function feels wrong
</blockquote></details>

what do you mean? do you prefer another forEach before filtering? or I'm misunderstanding? 

---

*[wct.conf.js, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaBSW5FUWLSHBvDvNZr:-KaDefkn4jLYKDlkpvQv:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/edb218d6e257abca66b0aae89a11e1b96f75446f/wct.conf.js#L1)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

`yargs` dependency should be  also removed from `package.json` as we're not using it anymore.
</blockquote></details>

Done.

---

*[wct.conf.js, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCBj_fjHq8UrKpmK7H:-KaDdIfhEpxVxq838a_2:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/887d0ff520afce807b712d79edf0df508ded1a8d/wct.conf.js#L16)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

We can't disable testing these browsers with P1. Maybe we also need wct.conf-2.0.js or something?
</blockquote></details>

Done.

---

*[demo/custom.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCC6nIIGdUAqJnf9ef:-KaDeYYwyspQA1zbUNa0:bvemjsb) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/edb218d6e257abca66b0aae89a11e1b96f75446f/demo/custom.html#L29)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

<custom-style> wrapper needed
</blockquote></details>

ops, Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47)*

**Comment by limonte** [comment]
Review status: 0 of 14 files reviewed at latest revision, 8 unresolved discussions.

---

*[gulpfile.js, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaBRrAfhxQ9OAXZdG6h:-KaGa1ZQAs8Q-EiQRW3h:be755j0) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/887d0ff520afce807b712d79edf0df508ded1a8d/gulpfile.js#L35)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

It's a convenience method for local testing.
I run this frequently, and it is already in other components. Is it there any impact to leave this here?
</blockquote></details>

No, I'm totally ok with it, just question :) Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-:-KaGaUBF5relfbIcKr2R:bnfp4nl)*

**Comment by tomivirkki** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[bower-2.0.json, line 30 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaGqAxgL6xNQc9G5hVw:-KaGqAxh8tQpljSjd7FJ:b489j2i) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/dd3ff49ad5d93b01e641fd43644ffa40c0417f55/bower-2.0.json#L30)):*
> ```JSON
>     "iron-demo-helpers": "polymerelements/iron-demo-helpers#2.0-preview",
>     "iron-test-helpers": "PolymerElements/iron-test-helpers#2.0-preview",
>     "test-fixture": "PolymerElements/test-fixture#custom-elements-v1",
> ```

Tag/branch custom-elements-v1 does not exist

---

*[vaadin-split-layout.html, line 275 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCBc44aD5SsaD-0HtP:-KaGuYJn2T9ORqFwFZLb:b-sjo9b6) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/887d0ff520afce807b712d79edf0df508ded1a8d/vaadin-split-layout.html#L275)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

what do you mean? do you prefer another forEach before filtering? or I'm misunderstanding? 
</blockquote></details>

Maybe it's better as it is. Could use a test though (the tests pass even if you leave out the `setAttribute` part)

Note: The filtering loop is actually unnecessary, you could achieve the same with `Polymer.dom(this).querySelectorAll('*:not(.splitter-handle)').forEach...`

---

*[demo/custom.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCC6nIIGdUAqJnf9ef:-KaGvs51bFzRTJnooxyW:b-v2wps3) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/edb218d6e257abca66b0aae89a11e1b96f75446f/demo/custom.html#L29)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

ops, Done.
</blockquote></details>

Typos: "cutsom-style"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47)*

**Comment by manolo** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[bower-2.0.json, line 30 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaGqAxgL6xNQc9G5hVw:-KaHBlh32sktJbHfMam4:b-10jbyy) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/dd3ff49ad5d93b01e641fd43644ffa40c0417f55/bower-2.0.json#L30)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Tag/branch custom-elements-v1 does not exist
</blockquote></details>

That branch was very recently merged and removed https://github.com/PolymerElements/iron-input/commit/14637e05e9cd8ad21dbfc38d7e4379157d6f189b

Done.

---

*[vaadin-split-layout.html, line 275 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCBc44aD5SsaD-0HtP:-KaHBtj0EPhM0JXUV5Zb:b-5oye3b) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/887d0ff520afce807b712d79edf0df508ded1a8d/vaadin-split-layout.html#L275)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Maybe it's better as it is. Could use a test though (the tests pass even if you leave out the `setAttribute` part)

Note: The filtering loop is actually unnecessary, you could achieve the same with `Polymer.dom(this).querySelectorAll('*:not(.splitter-handle)').forEach...`
</blockquote></details>

- Added the test.
- Tried css selectors but we need effective children in 2.0. So this code does not work if you replace 1.7 dependencies with 2.0:

```
_processChildren: function() {
  Polymer.dom(this).querySelectorAll('.splitter-handle').forEach(function(child) {
    Polymer.dom(child).setAttribute('slot', 'handle');
  });

  Polymer.dom(this).querySelectorAll('*:not(.splitter-handle)').forEach(function(child, i) {
    if (i === 0) {
      this._primaryChild = child;
      Polymer.dom(child).setAttribute('slot', 'primary');
    } else if (i == 1) {
      this._secondaryChild = child;
      Polymer.dom(child).setAttribute('slot', 'secondary');
    } else {
      Polymer.dom(child).removeAttribute('slot');
    }
  }.bind(this));
},
```

---

*[demo/custom.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-KaCC6nIIGdUAqJnf9ef:-KaHDJMD9dgqLHYSrqk8:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/edb218d6e257abca66b0aae89a11e1b96f75446f/demo/custom.html#L29)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Typos: "cutsom-style"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 6 of 13 files at r1, 4 of 5 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/47#-:-KaHfPBn6C7SoYF3J_p2:bnfp4nl)*

**Pull request merged**
