### PR TITLE
Improve documentation

### LINKED ISSUE #33: Improve documentation
Suggestions from DX tests:

- The split layout does not take all the height by default. The docs should communicate how to set height for the split layout element. Consider also the cases when a split layout has another split layout, and when a split layout contains a div with another split layout.
- The initial sizes and the limits sections in the API docs should be split.
- We should explain the reasons better why the splitter is resized with min-width and min-height.
- The documentation guides should contain up-to-date screenshots for the code examples.
- The styling guide should explicitly tell how to hide the handle.
- The overview guide is not an overview, but a hello world. This could be expanded to have a better introduction of the terms, the component features, and to reference the other guides.

### PR DESCRIPTION
**Pull request by platosha**
Fixes #33

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout/34)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm: 

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34#-:-KYTtydiMa7Zt8ToggdE:bg7igkv)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[docs/vaadin-split-layout-height.adoc, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34#-KYXbPLoqf-X7y3Cd0M3:-KYXbPLoqf-X7y3Cd0M4:b1ro9jb) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b8bcafbcc59f0168fa17fa6971e937cc243e2f36/docs/vaadin-split-layout-height.adoc#L1)):*
> ```AsciiDoc
> ---
> ```

Having a separate page in split layout documentation that explains how block element sizing works in HTML feels odd. Maybe just a mention about split layout being a block element is sufficient.

---

*[docs/vaadin-split-layout-overview.adoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34#-KYXdTBl8UfnsTkukqkL:-KYXdTBl8UfnsTkukqkM:b-doa1ri) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b8bcafbcc59f0168fa17fa6971e937cc243e2f36/docs/vaadin-split-layout-overview.adoc#L15)):*
> ```AsciiDoc
> ----
> <vaadin-split-layout>
>   <div>Elit laborum pariatur cumque accusamus ad Cum vel nobis molestiae esse est, reprehenderit? Excepturi soluta magnam voluptates totam rem porro. Cupiditate tempora nobis aspernatur reiciendis molestias. Perspiciatis delectus esse hic</div>
> ```

This example should probably match the image (which has "First/Second content element")

---

*[docs/vaadin-split-layout-styling.adoc, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34#-KYXhJ3cc_oaKj7cuX52:-KYXhJ3cc_oaKj7cuX53:b-g7ed4p) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b8bcafbcc59f0168fa17fa6971e937cc243e2f36/docs/vaadin-split-layout-styling.adoc#L16)):*
> ```AsciiDoc
> == Content Customization
> 
> The content elements are light DOM children. Therefore, you can style it by using normal CSS selectors in your application.
> ```

The second sentence should also be switched to plural ("it" -> "them").

Don't know if "light DOM children" is a familiar concept for (non-Polymer) developers.

---

*[docs/vaadin-split-layout-styling.adoc, line 62 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34#-KYXiOPHWcm9bsXuSWFA:-KYXiOPI5tYvR-T1t-y3:b-tiqipi) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b8bcafbcc59f0168fa17fa6971e937cc243e2f36/docs/vaadin-split-layout-styling.adoc#L62)):*
> ```AsciiDoc
> [NOTE]
> ====
> The splitter size is set using [propertyname]#min-width# and [propertyname]#min-height# elements. This allows to specify the thickness of the splitter for both `vertical` and `horizontal` layouts using a single mixin.
> ```

"elements" -> "properties"

---

*[docs/vaadin-split-layout-styling.adoc, line 124 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34#-KYXigm9mDXA-fb_1wau:-KYXigm9mDXA-fb_1wav:b-m52qdb) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b8bcafbcc59f0168fa17fa6971e937cc243e2f36/docs/vaadin-split-layout-styling.adoc#L124)):*
> ```AsciiDoc
> === Hiding the Handle
> 
> In order to hide the handle, use `fill: none;` in the splitter mixin:
> ```

"opacity: 0" might be more obvious and also agnostic to the handle internals (doesn't expect the handle to be an svg)?

---

*[docs/vaadin-split-layout-styling.adoc, line 162 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34#-KYXjItF2a9QTRyn-qdN:-KYXjItF2a9QTRyn-qdO:b-sdz6ee) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b8bcafbcc59f0168fa17fa6971e937cc243e2f36/docs/vaadin-split-layout-styling.adoc#L162)):*
> ```AsciiDoc
> image::img/vaadin-split-layout-custom-handle-icon.png[width="560"]
> 
> In order to have different icons for vertical and horizontal layouts, add two icons to your light DOM children, and use CSS to show or hide them depending on the `vertical` attribute of the [vaadinelement]#vaadin-split-layout#:
> ```

"..inside your vaadin-split-layout..." might be easier to understand than "light DOM children" (unfamiliar term for most users)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[docs/vaadin-split-layout-styling.adoc, line 124 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34#-KYXigm9mDXA-fb_1wau:-KYYF7Fwbr62-byuLSi9:bxugyck) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b8bcafbcc59f0168fa17fa6971e937cc243e2f36/docs/vaadin-split-layout-styling.adoc#L124)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

"opacity: 0" might be more obvious and also agnostic to the handle internals (doesn't expect the handle to be an svg)?
</blockquote></details>

`opacity: 0` will hide the splitter, not just the handle inside the splitter. Not appropriate here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34)*

**Comment by tomivirkki** [comment]
*[docs/vaadin-split-layout-styling.adoc, line 124 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34#-KYXigm9mDXA-fb_1wau:-KYYZaL8EsBUB-N6eBnG:bpuie) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b8bcafbcc59f0168fa17fa6971e937cc243e2f36/docs/vaadin-split-layout-styling.adoc#L124)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

`opacity: 0` will hide the splitter, not just the handle inside the splitter. Not appropriate here.
</blockquote></details>

Ah, true that. "fill" it is then

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34)*

**Comment by platosha** [comment]
Review status: 17 of 22 files reviewed at latest revision, 5 unresolved discussions.

---

*[docs/vaadin-split-layout-height.adoc, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34#-KYXbPLoqf-X7y3Cd0M3:-KYYoHFD2EiJsijyxrs5:b-kkf1z9) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b8bcafbcc59f0168fa17fa6971e937cc243e2f36/docs/vaadin-split-layout-height.adoc#L1)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Having a separate page in split layout documentation that explains how block element sizing works in HTML feels odd. Maybe just a mention about split layout being a block element is sufficient.
</blockquote></details>

I was considering it at first, but there could be users that are not familiar with the web platform that much to fully understand what does the “block element” means.

The DX tests revealed that developers sometimes don’t read the docs word-by-word, but rather scan for the relevant examples and read the code blocks.

Also, this is a pretty common use case, I believe. I don’t think that there’s any harm of explaining this with a few short examples in a separate page.

Added a mention of the block element behavior here, though.

---

*[docs/vaadin-split-layout-styling.adoc, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34#-KYXhJ3cc_oaKj7cuX52:-KYYtWear-mbGbtfyc6N:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b8bcafbcc59f0168fa17fa6971e937cc243e2f36/docs/vaadin-split-layout-styling.adoc#L16)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The second sentence should also be switched to plural ("it" -> "them").

Don't know if "light DOM children" is a familiar concept for (non-Polymer) developers.
</blockquote></details>

Done.

---

*[docs/vaadin-split-layout-styling.adoc, line 62 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34#-KYXiOPHWcm9bsXuSWFA:-KYYtY3oTj5-Mnd5m6dB:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b8bcafbcc59f0168fa17fa6971e937cc243e2f36/docs/vaadin-split-layout-styling.adoc#L62)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

"elements" -> "properties"
</blockquote></details>

Done.

---

*[docs/vaadin-split-layout-styling.adoc, line 162 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34#-KYXjItF2a9QTRyn-qdN:-KYYtcHTDGFv8urJIskt:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b8bcafbcc59f0168fa17fa6971e937cc243e2f36/docs/vaadin-split-layout-styling.adoc#L162)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

"..inside your vaadin-split-layout..." might be easier to understand than "light DOM children" (unfamiliar term for most users)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34)*

**Comment by platosha** [comment]
Review status: 17 of 22 files reviewed at latest revision, 5 unresolved discussions.

---

*[docs/vaadin-split-layout-overview.adoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34#-KYXdTBl8UfnsTkukqkL:-KYYtfbQdIjm3Vpi_8Vm:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b8bcafbcc59f0168fa17fa6971e937cc243e2f36/docs/vaadin-split-layout-overview.adoc#L15)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This example should probably match the image (which has "First/Second content element")
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r2.
Review status: 18 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/34#-:-KYm5lpsvXnM0onvfFJa:bnfp4nl)*

**Pull request merged**
