### PR TITLE
Convert to pure P2 ES6 class

### PR DESCRIPTION
**Pull request by manolo**
Connects to #65

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout/73)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[index.html, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/73#-Kn5bvwW2kosAYU2WZhf:-Kn5bvwW2kosAYU2WZhg:b-8ywz1y) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/802f757171526f8676bf8eb15b592348cceb0d2d/index.html#L12)):*
> ```HTML
>   </head>
>   <body>
>     <api-doc-viewer url="documentation.json" element-class-name="Vaadin.SplitLayoutElement"></api-doc-viewer>
> ```

Did you try if the `3.0.0-rc` versions of `<iron-component-page>` work with ES6 elements?

---

*[vaadin-split-layout.html, line 269 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/73#-Kn5cp-VoB_LsC2kMt0j:-Kn5cp-VoB_LsC2kMt0k:b-8w3tsq) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/802f757171526f8676bf8eb15b592348cceb0d2d/vaadin-split-layout.html#L269)):*
> ```HTML
>         ready() {
>           super.ready();
>           new Polymer.FlattenedNodesObserver(this, this._processChildren);
> ```

We probably want to store this observer into `this._observer` so that it can be flushed if needed. (in tests or while debugging)

---

*[vaadin-split-layout.html, line 345 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/73#-Kn5d2liq-QoLIXs_uVc:-Kn5d2liq-QoLIXs_uVd:b-52h9b) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/802f757171526f8676bf8eb15b592348cceb0d2d/vaadin-split-layout.html#L345)):*
> ```HTML
>          *
>          * @event iron-resize
>          */        
> ```

extra whitespaces

---

*[test/vaadin-split-layout_test.html, line 154 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/73#-Kn5dD7vFkqvKVPshc2M:-Kn5dD7vFkqvKVPshc2N:b-ahi61g) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/802f757171526f8676bf8eb15b592348cceb0d2d/test/vaadin-split-layout_test.html#L154)):*
> ```HTML
> 
>         it('has overflow visible', done => {
>           splitLayout.async(() => {
> ```

Rather use `Polymer.Async.microTask.run(..)` since this will break once we remove the `mixinBehaviors`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/73)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-split-layout.html, line 345 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/73#-Kn5d2liq-QoLIXs_uVc:-Kn895ffdHS_WjvRyKWZ:b7l1vns) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/802f757171526f8676bf8eb15b592348cceb0d2d/vaadin-split-layout.html#L345)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

extra whitespaces
</blockquote></details>

vscode does not help, in atom it was automatic to remove those. I need to take a look to the config.
Done.

---

*[test/vaadin-split-layout_test.html, line 154 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/73#-Kn5dD7vFkqvKVPshc2M:-Kn89aTtoid0vGZ3l5Pi:b-ya6bzl) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/802f757171526f8676bf8eb15b592348cceb0d2d/test/vaadin-split-layout_test.html#L154)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Rather use `Polymer.Async.microTask.run(..)` since this will break once we remove the `mixinBehaviors`
</blockquote></details>

Good catch, I forgot this case.
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/73)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-split-layout.html, line 269 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/73#-Kn5cp-VoB_LsC2kMt0j:-Kn89xbNamgRbx523Tsu:b-o7igyk) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/802f757171526f8676bf8eb15b592348cceb0d2d/vaadin-split-layout.html#L269)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

We probably want to store this observer into `this._observer` so that it can be flushed if needed. (in tests or while debugging)
</blockquote></details>

Since it would be an unused variable in code, I do prefer that it is added when needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/73)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[index.html, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/73#-Kn5bvwW2kosAYU2WZhf:-Kn8IX-hT_VOmDbhiF7t:blca9qd) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/802f757171526f8676bf8eb15b592348cceb0d2d/index.html#L12)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Did you try if the `3.0.0-rc` versions of `<iron-component-page>` work with ES6 elements?
</blockquote></details>

Tested and it works. Since this is something that should be done from the skeleton to all components, I leave this for a separate PR. Opened this working branch for now: https://github.com/vaadin/vaadin-split-layout/commits/es6_apidoc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/73)*

**Comment by Saulis** [comment]
Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/73)*

**Pull request merged**
