### PR TITLE
Adding demo for home page in webcomponents.org

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout/29)

### CODE REVIEW

**Comment by manolo** [comment]
Preview demo at https://beta.webcomponents.org/preview/vaadin/vaadin-split-layout/d0c26856673dbaf17bac116bb40912bcc697e381 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/29#-:-KXeSkPAljV1sKbCIsHA:bns08jg)*

**Comment by samiheikki** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/29#-KXijT0JnftkjqDiBJF_:-KXijRkmwCmih347YXdG:b-353gkh) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/d0c26856673dbaf17bac116bb40912bcc697e381/README.md#L18)):*
> ```Markdown
>      }
>      vaadin-split-layout > div {
>        font-family: sans-serif;
> ```

In our other elements the font-family is `'Roboto', 'Noto', sans-serif` (in that order). Are the first two unavailable in this place or can they be added?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/29)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/29#-KXijT0JnftkjqDiBJF_:-KXj7QvLh4bQQi7QCTIm:b-o54kn6) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/d0c26856673dbaf17bac116bb40912bcc697e381/README.md#L18)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

In our other elements the font-family is `'Roboto', 'Noto', sans-serif` (in that order). Are the first two unavailable in this place or can they be added?
</blockquote></details>

Roboto needs that you load the web font and import the roboto.html wc.
It's  something many people complains about because it's slow and sans-serif is pretty similar, so in PWAs for instance is a common practice.
It's supposed that this website already loads it, but this is run in an iframe, so we have to load it manually.
I wanted just to use sans-serif to speed up the loading, and avoid having the default times font in browser which does  not look nice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/29)*

**Comment by samiheikki** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/29#-:-KXjGNG48T9xqzwB9Tt0:bnfp4nl)*

**Pull request merged**
