### PR TITLE
Rename vertical attribute to orientation.

### LINKED ISSUE #87: Consider renaming `vertical` to `orientation`
To be consistent with `vaadin-tabs` (and possibly with `vaadin-ordered-layout`), rename the `vertical` property to `orientation`.

### PR DESCRIPTION
**Pull request by vicsstar**
Fixes #87

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout/89)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-split-layout.html, line 316 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-KzYU68GZ65Hw_HBgN48:-KzYU68HtCQ1dWSKuhWo:b-90zujp) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b4b38e5e99b974b95fe34edd23eb5e6f83251d89/vaadin-split-layout.html#L316)):*
> ```HTML
>           }
> 
>           var size = (this.orientation === 'vertical') ? 'height' : 'width';
> ```

you don't need to maintain parentheses in the ternary operator. 

---

*[vaadin-split-layout.html, line 327 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-KzYUPSm9Flh_AaKIx5V:-KzYUPSm9Flh_AaKIx5W:bm4y3dt) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b4b38e5e99b974b95fe34edd23eb5e6f83251d89/vaadin-split-layout.html#L327)):*
> ```HTML
>           }
> 
>           var distance = (this.orientation === 'vertical') ? event.detail.dy : event.detail.dx;
> ```

not needed parentheses

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[vaadin-split-layout.html, line 327 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-KzYUPSm9Flh_AaKIx5V:-KzYW0AxTlBfauiNnrHi:bb77ufg) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b4b38e5e99b974b95fe34edd23eb5e6f83251d89/vaadin-split-layout.html#L327)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

not needed parentheses
</blockquote></details>

Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[vaadin-split-layout.html, line 316 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-KzYU68GZ65Hw_HBgN48:-KzYVsECTxMWNRvve5CA:bf36dop) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b4b38e5e99b974b95fe34edd23eb5e6f83251d89/vaadin-split-layout.html#L316)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

you don't need to maintain parentheses in the ternary operator. 
</blockquote></details>

Yes I know. I just consider it good practice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[vaadin-split-layout.html, line 316 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-KzYU68GZ65Hw_HBgN48:-KzYWz1n632Lm77y8wJe:b-xrpom5) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b4b38e5e99b974b95fe34edd23eb5e6f83251d89/vaadin-split-layout.html#L316)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Yes I know. I just consider it good practice.
</blockquote></details>

The second one was longer. In cases like that, I believe it's better to show your intent whenever possible rather than obscure it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[vaadin-split-layout.html, line 327 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-KzYUPSm9Flh_AaKIx5V:-KzYXbgo7pwK-jZTfAx6:b-zaa4gs) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b4b38e5e99b974b95fe34edd23eb5e6f83251d89/vaadin-split-layout.html#L327)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

I should remove them for the purpose of this review at least.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[vaadin-split-layout.html, line 316 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-KzYU68GZ65Hw_HBgN48:-KzYYO36f3HMVnz1YBv9:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b4b38e5e99b974b95fe34edd23eb5e6f83251d89/vaadin-split-layout.html#L316)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

The second one was longer. In cases like that, I believe it's better to show your intent whenever possible rather than obscure it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[vaadin-split-layout.html, line 327 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-KzYUPSm9Flh_AaKIx5V:-KzYYPQHD60z8hG6WW5I:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b4b38e5e99b974b95fe34edd23eb5e6f83251d89/vaadin-split-layout.html#L327)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

I should remove them for the purpose of this review at least.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by manolo** [comment]
Please rebase with master, then :lgtm_strong: 

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-split-layout.html, line 316 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-KzYU68GZ65Hw_HBgN48:-KzYtthhNKO2fzwg6vF_:b-t6mx4c) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b4b38e5e99b974b95fe34edd23eb5e6f83251d89/vaadin-split-layout.html#L316)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

IMO extra parenthesis does no add anything but confusion because I think that the author needs to stress some unexpected behaviour in the expression. 
So reserve them for complex expressions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-:-KzYuGltYMLeWXDO3fvw:bqxwx64)*

**Comment by platosha** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-split-layout.html, line 255 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-KzbzHC6CHQc1rQ87Lam:-KzbzHC6CHQc1rQ87Lan:b-samwc2) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/3ef20ecf25daeba0690f7a7607183d55b5655357/vaadin-split-layout.html#L255)):*
> ```HTML
>           return {
>             /**
>              * Change the split layout's orientation (can be one of `horizontal`|`vertical`).
> ```

BTW Perviously, the word `Change` was here because of the boolean type, meaning: either change or not change the orientation from default horizontal.

No longer needed, I think, could be simply described as:

`The orientation of the split layout. Can be either `'horizontal'` or `'vertical'.`.

Not a blocker though.

---

*[vaadin-split-layout.html, line 256 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-KzbzkhP2ef6R10DhQ8s:-KzbzkhP2ef6R10DhQ8t:b-ptviyo) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/3ef20ecf25daeba0690f7a7607183d55b5655357/vaadin-split-layout.html#L256)):*
> ```HTML
>             /**
>              * Change the split layout's orientation (can be one of `horizontal`|`vertical`).
>              * Defaults to `horizontal`.
> ```

BTW Default values are automatically indicated from specified static `value: ''` in the property descriptor. No need to describe the default value in text.

---

*[vaadin-split-layout.html, line 256 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-Kzc-On52RtxcpG4nJk6:-Kzc-On52RtxcpG4nJk7:bcogbnb) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/3ef20ecf25daeba0690f7a7607183d55b5655357/vaadin-split-layout.html#L256)):*
> ```HTML
>             /**
>              * Change the split layout's orientation (can be one of `horizontal`|`vertical`).
>              * Defaults to `horizontal`.
> ```

Mind that backticks like \`something\` indicate code.

String values should be expressed in quotes and backticks (\`'vertical'\`, \`'horizontal'\`), meaning “string in code”.

Without additional string quotes, \`vertical\` looks like a JS name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by YuriyVaadin** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by tomivirkki** [comment]
@vicsstar can you rebase this on master and respond to unanswered comments. Would like to have this API change in 4.0.0

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-:-L0ABZVAgjefYIp4dWEt:bzgzcib)*

**Comment by vicsstar** [comment]
*[vaadin-split-layout.html, line 316 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-KzYU68GZ65Hw_HBgN48:-L0AL7W9y5GMdHG3MsK7:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/b4b38e5e99b974b95fe34edd23eb5e6f83251d89/vaadin-split-layout.html#L316)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

IMO extra parenthesis does no add anything but confusion because I think that the author needs to stress some unexpected behaviour in the expression. 
So reserve them for complex expressions.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[vaadin-split-layout.html, line 255 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-KzbzHC6CHQc1rQ87Lam:-L0ALBuc7AMaPpSp6c-h:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/3ef20ecf25daeba0690f7a7607183d55b5655357/vaadin-split-layout.html#L255)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW Perviously, the word `Change` was here because of the boolean type, meaning: either change or not change the orientation from default horizontal.

No longer needed, I think, could be simply described as:

`The orientation of the split layout. Can be either `'horizontal'` or `'vertical'.`.

Not a blocker though.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[vaadin-split-layout.html, line 256 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-KzbzkhP2ef6R10DhQ8s:-L0ALHWuQkSa5ssu6KuY:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/3ef20ecf25daeba0690f7a7607183d55b5655357/vaadin-split-layout.html#L256)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW Default values are automatically indicated from specified static `value: ''` in the property descriptor. No need to describe the default value in text.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[vaadin-split-layout.html, line 256 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-Kzc-On52RtxcpG4nJk6:-L0ALJQ4u0oICGO2SDLe:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/3ef20ecf25daeba0690f7a7607183d55b5655357/vaadin-split-layout.html#L256)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Mind that backticks like \`something\` indicate code.

String values should be expressed in quotes and backticks (\`'vertical'\`, \`'horizontal'\`), meaning “string in code”.

Without additional string quotes, \`vertical\` looks like a JS name.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by web-padawan** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[src/vaadin-split-layout.html, line 12 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-L0JENyUAEu0R82UxgWK:-L0JENyUAEu0R82UxgWL:be34jkp) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/be83368c6ed12656aecbc92d5130c9236619abcf/src/vaadin-split-layout.html#L12)):*
> ```HTML
> <link rel="import" href="../../iron-resizable-behavior/iron-resizable-behavior.html">
> <link rel="import" href="../../vaadin-themable-mixin/vaadin-themable-mixin.html">
> <link rel="import" href="../../vaadin-element-mixin/vaadin-element-mixin.html">
> ```

Looks like a bad merge. These imports shouldn't have been changed

---

*[src/vaadin-split-layout.html, line 13 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-L0JEUw5nPvfltIwl75y:-L0JEUw647_1vQUxlwMS:b-g2ntq5) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/1fd144bce8afa1e6cfef20112ba8c33f6b5400bd/src/vaadin-split-layout.html#L13)):*
> ```HTML
> <link rel="import" href="../vaadin-themable-mixin/vaadin-themable-mixin.html">
> 
> <dom-module id="vaadin-split-layout-default-theme" theme-for="vaadin-split-layout">
> ```

Same here, the bad merge: default theme was dropped when switching to Valo

---

*[src/vaadin-split-layout.html, line 258 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-L0JEhPXiuUCrnb7Ej8s:-L0JEhPXiuUCrnb7Ej8t:b-277j1k) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/1fd144bce8afa1e6cfef20112ba8c33f6b5400bd/src/vaadin-split-layout.html#L258)):*
> ```HTML
>           return {
>             /**
>              * Split layout's orientation (can be one of "horizontal" or "vertical").
> ```

Consider using the same value listing syntax as [vaadin-list-mixin](https://github.com/vaadin/vaadin-list-mixin/blob/master/vaadin-list-mixin.html#L36) has for consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[src/vaadin-split-layout.html, line 12 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-L0JENyUAEu0R82UxgWK:-L0JIqGdWE3AP1zxQRfM:b-3kmu89) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/be83368c6ed12656aecbc92d5130c9236619abcf/src/vaadin-split-layout.html#L12)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Looks like a bad merge. These imports shouldn't have been changed
</blockquote></details>

Was an issue with the change I accepted using VS Code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[src/vaadin-split-layout.html, line 12 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-L0JENyUAEu0R82UxgWK:-L0JIymMjcpQhwSGHWhX:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/be83368c6ed12656aecbc92d5130c9236619abcf/src/vaadin-split-layout.html#L12)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Was an issue with the change I accepted using VS Code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[src/vaadin-split-layout.html, line 13 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-L0JEUw5nPvfltIwl75y:-L0JJ-NUSVWpo4iHTUi5:bjo6vlj) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/1fd144bce8afa1e6cfef20112ba8c33f6b5400bd/src/vaadin-split-layout.html#L13)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Same here, the bad merge: default theme was dropped when switching to Valo
</blockquote></details>

Yep. Same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[src/vaadin-split-layout.html, line 13 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-L0JEUw5nPvfltIwl75y:-L0JJ1n74dneNbJ3f5ak:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/1fd144bce8afa1e6cfef20112ba8c33f6b5400bd/src/vaadin-split-layout.html#L13)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Yep. Same.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[src/vaadin-split-layout.html, line 258 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-L0JEhPXiuUCrnb7Ej8s:-L0JKq9O0QefpgYe9jkW:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/1fd144bce8afa1e6cfef20112ba8c33f6b5400bd/src/vaadin-split-layout.html#L258)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Consider using the same value listing syntax as [vaadin-list-mixin](https://github.com/vaadin/vaadin-list-mixin/blob/master/vaadin-list-mixin.html#L36) has for consistency.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by web-padawan** [comment]
Reviewed 2 of 3 files at r4.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by web-padawan** [comment]
Reviewed 1 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/vaadin-split-layout.html, line 87 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-L0K-Bl0MbXuSHXoyw3Y:-L0K-Bl0MbXuSHXoyw3Z:b1bpggs) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6bf9ec2792c2a7b96af9dede07743fd33f25ed52/src/vaadin-split-layout.html#L87)):*
> ```HTML
>        * positioned side by side in a flex container with a horizontal layout.
>        *
>        * You can change the split mode to vertical by setting the `orientation` attribute to "vertical":
> ```

OK nit: \`"vertical"\`.

---

*[src/vaadin-split-layout.html, line 236 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-L0K-LjtWVwSXki5Qj4I:-L0K-LjtWVwSXki5Qj4J:b-6knfwp) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6bf9ec2792c2a7b96af9dede07743fd33f25ed52/src/vaadin-split-layout.html#L236)):*
> ```HTML
>           return {
>             /**
>              * Change the split layout's orientation. Possible values are: `horizontal|vertical`.
> ```

OK one more nit: a special notation for options is bit confusing, would be better list the separate options as a plain language list of strings:
```
... Possible values are: `"horizontal"`, `"vertical"`.
```

These values are wrapped in backticks to indicate code (markdown will turn backticks into a highlight with a monospace font), and also wrapped in quotes to show that these a string constants.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/vaadin-split-layout.html, line 236 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-L0K-LjtWVwSXki5Qj4I:-L0K37syhQ5KcJOP074d:b-aswkqq) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6bf9ec2792c2a7b96af9dede07743fd33f25ed52/src/vaadin-split-layout.html#L236)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

OK one more nit: a special notation for options is bit confusing, would be better list the separate options as a plain language list of strings:
```
... Possible values are: `"horizontal"`, `"vertical"`.
```

These values are wrapped in backticks to indicate code (markdown will turn backticks into a highlight with a monospace font), and also wrapped in quotes to show that these a string constants.
</blockquote></details>

@platosha it was actually suggested by me to use the same syntax as in the `vaadin-list-mixin` and also `vaadin-notification` and it seems that we have different opinions on this. 

I am not opposite to your suggestion but would prefer using the same syntax consistently regardless of how many possible values does the given property support.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[src/vaadin-split-layout.html, line 236 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-L0K-LjtWVwSXki5Qj4I:-L0K4wjIGWD6EYj2LR2G:b6253rv) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6bf9ec2792c2a7b96af9dede07743fd33f25ed52/src/vaadin-split-layout.html#L236)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

@platosha it was actually suggested by me to use the same syntax as in the `vaadin-list-mixin` and also `vaadin-notification` and it seems that we have different opinions on this. 

I am not opposite to your suggestion but would prefer using the same syntax consistently regardless of how many possible values does the given property support.
</blockquote></details>

Okay, obviously there's a difference in opinion but, any of them would actually work. We also need to understand that the end users we're serving are developers and most would understand both notations - I would. So I need us to decide on what to stick with.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[src/vaadin-split-layout.html, line 87 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-L0K-Bl0MbXuSHXoyw3Y:-L0KLcpVgcgmMqZk2ueB:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6bf9ec2792c2a7b96af9dede07743fd33f25ed52/src/vaadin-split-layout.html#L87)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

OK nit: \`"vertical"\`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by vicsstar** [comment]
*[src/vaadin-split-layout.html, line 236 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-L0K-LjtWVwSXki5Qj4I:-L0KpYKwRo7npqSw3EM5:babt321) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/6bf9ec2792c2a7b96af9dede07743fd33f25ed52/src/vaadin-split-layout.html#L236)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Okay, obviously there's a difference in opinion but, any of them would actually work. We also need to understand that the end users we're serving are developers and most would understand both notations - I would. So I need us to decide on what to stick with.
</blockquote></details>

Or we can leave it as is. As we've since not gotten a response, it looks like that's the consensus.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by tomivirkki** [comment]
Readme examples still use the old property `vertical`

---

Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/vaadin-split-layout.html, line 27 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-L0O_YC5t2N3jQJbLePk:-L0O_YC5t2N3jQJbLePl:b5nfd9w) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/47f0e0128bfd10bbb902d9be04c0549951ba3c3f/src/vaadin-split-layout.html#L27)):*
> ```HTML
>       }
> 
>       :host([orientation="vertical"]) {
> ```

Need to apply the same changes to the default valo theme

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-:-L0O_f93gFGy98TOjvW3:b-je9n3i)*

**Comment by tomivirkki** [comment]
*[src/vaadin-split-layout.html, line 27 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-L0O_YC5t2N3jQJbLePk:-L0OpC8dK1epqJXKkIiM:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/47f0e0128bfd10bbb902d9be04c0549951ba3c3f/src/vaadin-split-layout.html#L27)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Need to apply the same changes to the default valo theme
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r1, 1 of 2 files at r2, 1 of 3 files at r4, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-:-L0OpRAIII6D8x-Rc7sZ:bnfp4nl)*

**Comment by web-padawan** [comment]
@vicsstar please also update visual tests, as they use the old syntax now.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-:-L0P-wRZG1gsL9O71Rm6:b-rcfobz)*

**Comment by web-padawan** [comment]
:lgtm: 

---

Reviewed 3 of 6 files at r1, 1 of 2 files at r2, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/89#-:-L0PESsAe-HQjTrRk7B7:bg7igkv)*

**Pull request merged**
