### PR TITLE
Add `splitter-dragend` event API

### LINKED ISSUE #85: Flow API related todo list
### Resize events for server side

- [ ] ❓add a debounced resize-like event suitable for servers, so that there is a single event dispatched after the user have stopped dragging the splitter (event name to be decided)

### PR DESCRIPTION
**Pull request by platosha**
Fixes #85

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout/97)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-split-layout_test.html, line 298 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/97#-L3YAnDvA3mwKPeW4Ol9:-L3YAnDvA3mwKPeW4OlA:b-lt7njg) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/dbc7eb89b096be1689b5a463e66739d9ad65a475/test/vaadin-split-layout_test.html#L298)):*
> ```HTML
>           });
> 
>           it('should displatch `splitter-dragend` event', () => {
> ```

typo: `displatch` (remove "l")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/97)*

**Comment by platosha** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-split-layout_test.html, line 298 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/97#-L3YAnDvA3mwKPeW4Ol9:-L3YBrYS7fH4EsOguRen:b-896fix) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/dbc7eb89b096be1689b5a463e66739d9ad65a475/test/vaadin-split-layout_test.html#L298)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

typo: `displatch` (remove "l")
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/97)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/97#-:-L3Z6uvh6nxITOK3fiPb:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/vaadin-split-layout.html, line 328 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/97#-L3bkNhxuAR8lIknfk8L:-L3bkNhyIvSw957_6uaV:b-35htsg) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/344631dbe7976717a8c6b12e324ec1c6320043d3/src/vaadin-split-layout.html#L328)):*
> ```HTML
> 
>         /**
>          * Fired after dragging the splitter have ended.
> ```

nit: This description didn't make it to analysis.json

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/97#-:-L3bjs5dt2SNpBNnwtdc:bnfp4nl)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-split-layout.html, line 328 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/97#-L3bkNhxuAR8lIknfk8L:-L3bp4djTAYPdSRDw0m1:b-fximhy) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/344631dbe7976717a8c6b12e324ec1c6320043d3/src/vaadin-split-layout.html#L328)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

nit: This description didn't make it to analysis.json
</blockquote></details>

the fix should be in the next version of the analyzer: Polymer/polymer-analyzer#838
not sure if we can get this working until new major of the `polymer-cli`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/97)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/vaadin-split-layout.html, line 328 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/97#-L3bkNhxuAR8lIknfk8L:-L3bwtyEgN4LsMn6o_P5:b-ijuy7g) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/344631dbe7976717a8c6b12e324ec1c6320043d3/src/vaadin-split-layout.html#L328)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

the fix should be in the next version of the analyzer: Polymer/polymer-analyzer#838
not sure if we can get this working until new major of the `polymer-cli`
</blockquote></details>

ok, got it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/97)*

**Pull request merged**
