### PR TITLE
Depend on Polymer 2 by default

### PR DESCRIPTION
**Pull request by manolo**
Connects to #63

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout/64)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/64#-:-KjqdrWducdBUPqy6akO:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[wct.conf.js, line 12 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/64#-KkATHQjKc2_PGZF0JFB:-KkATHQjKc2_PGZF0JFC:b-ofemfo) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/cd2721fe47da9ee757221bdcb85ef4b9d36d98f0/wct.conf.js#L12)):*
> ```JavaScript
>       'OS X 10.11/ipad@9.3',
>       'Windows 10/microsoftedge@14',
>       'Windows 10/internet explorer@11',
> ```

Removed by accident?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/64)*

**Comment by limonte** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[wct.conf.js, line 12 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/64#-KkATHQjKc2_PGZF0JFB:-KkLB2o3RgsUXHVEjO6l:b-6k349l) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/cd2721fe47da9ee757221bdcb85ef4b9d36d98f0/wct.conf.js#L12)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Removed by accident?
</blockquote></details>

`iron-test-helpers` is broken. We will reenable IE tests after https://github.com/PolymerElements/iron-test-helpers/pull/88 is merged. Hopefully, it will tale a little bit less than ages for Polymer team to take a look. This PR is good to merge, I ensured manually that `split-layout` is working in both P1 and P2 versions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/64)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[wct.conf.js, line 12 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/64#-KkATHQjKc2_PGZF0JFB:-KkLF7CiP9PH2Oscf1n-:b-uofkkp) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/cd2721fe47da9ee757221bdcb85ef4b9d36d98f0/wct.conf.js#L12)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

`iron-test-helpers` is broken. We will reenable IE tests after https://github.com/PolymerElements/iron-test-helpers/pull/88 is merged. Hopefully, it will tale a little bit less than ages for Polymer team to take a look. This PR is good to merge, I ensured manually that `split-layout` is working in both P1 and P2 versions.
</blockquote></details>

Ok (although disabling the failing tests for IE would have been safer than disabling all the tests)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/64#-:-KkLFdx4UDA2ePmVgD50:bnfp4nl)*

**Comment by limonte** [comment]
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---

*[wct.conf.js, line 12 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/64#-KkATHQjKc2_PGZF0JFB:-KkLGO8DAAOcqmzA2Lj3:b-cgnbm2) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/cd2721fe47da9ee757221bdcb85ef4b9d36d98f0/wct.conf.js#L12)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Ok (although disabling the failing tests for IE would have been safer than disabling all the tests)
</blockquote></details>

True that, but it was more than a half of tests to disable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/64)*

**Comment by tomivirkki** [comment]
*[wct.conf.js, line 12 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/64#-KkATHQjKc2_PGZF0JFB:-KkLGl5ba556-iczK0Z2:b6b58gt) ([raw file](https://github.com/vaadin/vaadin-split-layout/blob/cd2721fe47da9ee757221bdcb85ef4b9d36d98f0/wct.conf.js#L12)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

True that, but it was more than a half of tests to disable
</blockquote></details>

Ok, I see. I'm fine with this :shipit:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/64)*

**Comment by manolo** [comment]
Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout/64)*

**Pull request merged**
